flex:
  version: 0.5.6
  workflows:
    provision-library:
      command: ./project-archetypes/library/provision-new.sh
    provision-service:
      command: ./project-archetypes/service/provision-new.sh
service:
  name: development-infrastructure
