on: 
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:

        - name: echo "Hello, World!"
